spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:5432}/${RDS_DB_NAME:ecommerce_db}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}

# Redis use AWS ElastiCache or keep containerized
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# Production logging
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.com.ecommerce.project=INFO